#############################################################################
# Makefile for building: mash.app/Contents/MacOS/mash
# Generated by qmake (2.01a) (Qt 4.5.2) on: lun. août 3 23:26:31 2009
# Project:  mash.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile mash.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.5/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtXml -framework QtGui -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Highlighter.cpp \
		highlighterhtml.cpp \
		main.cpp \
		mainFen.cpp \
		qtc-gdbmacros/gdbmacros.cpp moc_Highlighter.cpp \
		moc_highlighterhtml.cpp \
		moc_mainFen.cpp \
		qrc_ressources.cpp
OBJECTS       = Highlighter.o \
		highlighterhtml.o \
		main.o \
		mainFen.o \
		gdbmacros.o \
		moc_Highlighter.o \
		moc_highlighterhtml.o \
		moc_mainFen.o \
		qrc_ressources.o
DIST          = /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf \
		mash.pro
QMAKE_TARGET  = mash
DESTDIR       = 
TARGET        = mash.app/Contents/MacOS/mash

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile mash.app/Contents/PkgInfo mash.app/Contents/Resources/empty.lproj mash.app/Contents/Info.plist mash.app/Contents/Resources/TextEditor.icns $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) mash.app/Contents/MacOS/ || $(MKDIR) mash.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mash.pro  /usr/local/Qt4.5/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile mash.pro
/usr/local/Qt4.5/mkspecs/common/unix.conf:
/usr/local/Qt4.5/mkspecs/common/mac.conf:
/usr/local/Qt4.5/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.5/mkspecs/qconfig.pri:
/usr/local/Qt4.5/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.5/mkspecs/features/qt_config.prf:
/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.5/mkspecs/features/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.5/mkspecs/features/debug.prf:
/usr/local/Qt4.5/mkspecs/features/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.5/mkspecs/features/warn_on.prf:
/usr/local/Qt4.5/mkspecs/features/qt.prf:
/usr/local/Qt4.5/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.5/mkspecs/features/moc.prf:
/usr/local/Qt4.5/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.5/mkspecs/features/resources.prf:
/usr/local/Qt4.5/mkspecs/features/uic.prf:
/usr/local/Qt4.5/mkspecs/features/yacc.prf:
/usr/local/Qt4.5/mkspecs/features/lex.prf:
/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile mash.pro

mash.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) mash.app/Contents || $(MKDIR) mash.app/Contents 
	@$(DEL_FILE) mash.app/Contents/PkgInfo
	@echo "APPL????" >mash.app/Contents/PkgInfo
mash.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) mash.app/Contents/Resources || $(MKDIR) mash.app/Contents/Resources 
	@touch mash.app/Contents/Resources/empty.lproj
	
mash.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) mash.app/Contents || $(MKDIR) mash.app/Contents 
	@$(DEL_FILE) mash.app/Contents/Info.plist
	@sed -e "s,@ICON@,TextEditor.icns,g" -e "s,@EXECUTABLE@,mash,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.5/mkspecs/macx-g++/Info.plist.app >mash.app/Contents/Info.plist
mash.app/Contents/Resources/TextEditor.icns: TextEditor.icns
	@$(CHK_DIR_EXISTS) mash.app/Contents/Resources/ || $(MKDIR) mash.app/Contents/Resources/ 
	@$(DEL_FILE) mash.app/Contents/Resources/TextEditor.icns
	@$(COPY_FILE) TextEditor.icns mash.app/Contents/Resources/TextEditor.icns
dist: 
	@$(CHK_DIR_EXISTS) .tmp/mash1.0.0 || $(MKDIR) .tmp/mash1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mash1.0.0/ && $(COPY_FILE) --parents Highlighter.h highlighterhtml.h mainFen.h .tmp/mash1.0.0/ && $(COPY_FILE) --parents ressources.qrc .tmp/mash1.0.0/ && $(COPY_FILE) --parents Highlighter.cpp highlighterhtml.cpp main.cpp mainFen.cpp qtc-gdbmacros/gdbmacros.cpp .tmp/mash1.0.0/ && $(COPY_FILE) --parents aquaash_en.ts aquaash_es.ts .tmp/mash1.0.0/ && (cd `dirname .tmp/mash1.0.0` && $(TAR) mash1.0.0.tar mash1.0.0 && $(COMPRESS) mash1.0.0.tar) && $(MOVE) `dirname .tmp/mash1.0.0`/mash1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mash1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r mash.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_Highlighter.cpp moc_highlighterhtml.cpp moc_mainFen.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Highlighter.cpp moc_highlighterhtml.cpp moc_mainFen.cpp
moc_Highlighter.cpp: Highlighter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Highlighter.h -o moc_Highlighter.cpp

moc_highlighterhtml.cpp: highlighterhtml.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ highlighterhtml.h -o moc_highlighterhtml.cpp

moc_mainFen.cpp: Highlighter.h \
		highlighterHTML.h \
		mainFen.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainFen.h -o moc_mainFen.cpp

compiler_rcc_make_all: qrc_ressources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ressources.cpp
qrc_ressources.cpp: ressources.qrc \
		libqscintilla2.5.dylib \
		ressources/images/editpaste-256.png \
		ressources/images/fileopen-256.png \
		ressources/images/editcut-256.png \
		ressources/images/editcut-256.png \
		ressources/images/exec-256.png \
		ressources/images/filesaveas-256.png \
		ressources/images/editcopy-256.png \
		ressources/images/TextEditor.png \
		ressources/images/filenew-256.png \
		ressources/images/filesave-256.png \
		ressources/images/tab_remove-256.png \
		ressources/texte/scratch.txt
	/Developer/Tools/Qt/rcc -name ressources ressources.qrc -o qrc_ressources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

Highlighter.o: Highlighter.cpp Highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Highlighter.o Highlighter.cpp

highlighterhtml.o: highlighterhtml.cpp highlighterhtml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highlighterhtml.o highlighterhtml.cpp

main.o: main.cpp mainFen.h \
		Highlighter.h \
		highlighterHTML.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainFen.o: mainFen.cpp mainFen.h \
		Highlighter.h \
		highlighterHTML.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainFen.o mainFen.cpp

gdbmacros.o: qtc-gdbmacros/gdbmacros.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gdbmacros.o qtc-gdbmacros/gdbmacros.cpp

moc_Highlighter.o: moc_Highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Highlighter.o moc_Highlighter.cpp

moc_highlighterhtml.o: moc_highlighterhtml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highlighterhtml.o moc_highlighterhtml.cpp

moc_mainFen.o: moc_mainFen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainFen.o moc_mainFen.cpp

qrc_ressources.o: qrc_ressources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ressources.o qrc_ressources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

